version: "3"
services:
  web:
    image: mybankjdbc
    ports:
      - "8888:8080"
    networks:
      - net
    depends_on:
      - mysqldb
    restart: always 
  mysqldb:
    image: mysql:8
    networks:
      - net
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mybankdb  
    volumes:
      - dv:/var/lib/mysql
networks:
  net:
volumes:
  dv:
