version: '3.7'
services:
  mysqldb:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mybankdb
    volumes:
      - my-datavolume:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - my-overlay-network
  web:
    image: pbeniwal/mybankjdbc:v1
    ports:
      - "8888:8080"
    networks:
      - my-overlay-network
volumes:
  my-datavolume:
networks:
  my-overlay-network:
    driver: overlay

